articles/urls.py
from django.urls import path
from django.conf.urls import include, url

from .views import detail

app_name = 'articles'
urlpatterns = [
    path(r'<slug:slug>-<int:id>/', detail, name='detail'),
]

simpleblog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from articles.views import list_articles

urlpatterns = [
    re_path(r'^articles/', include('articles.urls', namespace='articles')),
    path('', list_articles, name='articles_list'),
    re_path(r'^users/', include('users.urls', namespace='users')),
    path('admin-blog/', admin.site.urls),
]

users/urls.py
from django.urls import path

app_name = 'users'
urlpatterns = [

]

articles/models.py
from django.db import models
from django.utils.text import slugify
from users.models import UserProfile, BaseModel

class Article(BaseModel):
    author = models.ForeignKey(
        UserProfile,
        verbose_name = "Auteur de l'article",
        on_delete=models.CASCADE,
    )
    title = models.TextField(
        verbose_name = "Titre de l'article",
        help_text = "Ce titre sera affiché en haut en h1 et sera en title de la page. Garder 50-60 caractères si possible.",
        max_length = 100,
    )
    subtitle = models.TextField(
        verbose_name = "Sous-titre de l'article",
        max_length = 100,
    )
    content = models.TextField(
        verbose_name = "Contenu de l'article",
        help_text = "Le contenu de l'article est en HTML",
    )
    slug = models.TextField(
        verbose_name = "Sous-URL de l'article",
        help_text = "Ce champ sera présent dans l'URL de l'article pour aider le référencement et donner du sens à l'URL.",
    )
    is_display = models.BooleanField(
        verbose_name = "Article visible ?",
        help_text = "Définit si l'article doit être consultable",
        default = True,
    )
    is_index = models.BooleanField(
        verbose_name = "Article indéxé ?",
        help_text = "Définit si l'article doit être indexé et affiché sur la liste des articles",
        default = True,
    )

    def __str__(self):
        return "%s (%s)" % (self.title, self.author)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

users/models.py
# coding: utf8
from django.db import models
from django.contrib.auth.models import AbstractUser

class BaseModel(models.Model):
    created = models.DateTimeField(
        auto_now_add = True, 
        verbose_name="Date de création"
    )
    modified = models.DateTimeField(
        auto_now = True, 
        verbose_name="Date de modification"
    )

    class Meta:
        abstract = True
        ordering = ("-created", )

class UserProfile(AbstractUser, BaseModel):
    displayed_name = models.TextField(
        verbose_name = "Nom d'affichage",
        help_text = "Ce nom sera affiché en tant qu'auteur des articles",
        null = True, 
        blank = True,
    )

    def __str__(self):
        if self.displayed_name:
            return "%s, %s" % (self.displayed_name, self.username)
        else:
            return "NOT DEFINED, %s" % (self.username)


            

articles/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404

from .models import Article

def list_articles(request):
    all_articles = Article.objects.filter(is_displayed=True, is_indexed=True)
    paginator = Paginator(all_articles, 10)
    page = request.GET.get('page')
    try:
        articles = paginator.get_page(page)
    except PageNotAnInteger:
        articles = paginator.get_page(1)
    except EmptyPage:
        articles = paginator.get_page(paginator.num_pages)
    return render(request, 'articles/list.html', {'articles': articles})

def detail(request, slug, id) :
    article = get_object_or_404(Article, id=id, isdisplay=True)
    return render(
        request,
        'articles/detail.html',
        { 'article' : article, }
    )

users/views.py
from django.shortcuts import render

# Create your views here.

simpleblog/templates/articles/list.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% for article in articles %}
                    <div class="post-preview">
                        <a href="{% url 'article_detail' article.slug article.id %}">
                            <h2 class="post-title">
                                {{ article.title }}
                            </h2>
                            <h3 class="post-subtitle">
                                {{ article.subtitle }}
                            </h3>
                        </a>
                        <p class="post-meta">
                            Posté par
                            <b>{{ article.author.displayed_name }}</b>
                            le {{ article.created }}
                        </p>
                    </div>
                    <hr>
                {% endfor %}
            </div>
        </div>

        <div class="clearfix">
            <span class="step-links">
                {% if articles.has_previous %}
                    <a class="btn btn-primary" href="?page={{ articles.previous_page_number }}">Précédent</a>
                {% endif %}

                <span class="current">
                    Page {{ articles.number }} sur {{ articles.paginator.num_pages }}.
                </span>

                {% if articles.has_next %}
                    <a class="btn btn-primary" href="?page={{ articles.next_page_number }}">Suivant</a>
                {% endif %}        
            </span>
        </div>
    </div>
{% endblock content %}

simpleblog/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    {% load staticfiles %}

<link href="{% static 'lib/css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'lib/css/fontawesome-free/all.min.css' %}" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
<link href="{% static 'lib/css/clean-blog/clean-blog.min.css' %}" rel="stylesheet">

    {% block head_end %} {% endblock head_end %}

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="">Articles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'articles:detail' 'a-propos' 1 %}">À propos</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block body_header %} {% endblock body_header %}
    {% block content %} {% endblock content %}
    <hr />
    {% block body_footer %} {% endblock body_footer %}

    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="js/clean-blog.min.js"></script>
</body>
</html>

simpleblog/templates/base_blog.html
{% extends "base.html" %}

{% block body_header %}
    <header class="masthead" style="background-image: url('https://img.freepik.com/photos-gratuite/abstrait-bleu-degrade-bleu-fonce-lisse-vignette-noire-studio_1258-53689.jpg');">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>{% block h1 %}{% endblock h1 %}</h1>
                        <span class="subheading">{% block subheading %}{% endblock subheading %}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock body_header %}

{% block body_footer %}
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2023</p>
            </div>
        </div>
    </div>
</footer>
{% endblock body_footer %}